{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major": 8, "minor": 5, "revision": 5, "architecture": "x64", "modernui": 1},
    "classnamespace": "dsp.toplevel",
    "rect": [80, 80, 1120, 720],
    "openinpresentation": 1,
    "default_fontname": "Arial",
    "default_fontsize": 11,
    "boxes": [
      {"box":{"id":"title","maxclass":"comment","text":"DARKSCO FIELD v0.1 — 64 voice generative field instrument","presentation":1,"presentation_rect":[16,12,430,24],"patching_rect":[20,15,430,24],"fontsize":14,"fontface":1}},
      {"box":{"id":"density","maxclass":"live.dial","parameter_enable":1,"varname":"Density","presentation":1,"presentation_rect":[18,55,52,52],"patching_rect":[30,75,52,52],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Density","parameter_shortname":"Density","parameter_mmin":0.0,"parameter_mmax":1.0,"parameter_initial":[0.42],"parameter_type":0}}}},
      {"box":{"id":"spread","maxclass":"live.dial","parameter_enable":1,"varname":"Spread","presentation":1,"presentation_rect":[86,55,52,52],"patching_rect":[100,75,52,52],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Spread","parameter_shortname":"Spread","parameter_mmin":0.0,"parameter_mmax":1.0,"parameter_initial":[0.72],"parameter_type":0}}}},
      {"box":{"id":"motion","maxclass":"live.dial","parameter_enable":1,"varname":"Motion","presentation":1,"presentation_rect":[154,55,52,52],"patching_rect":[170,75,52,52],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Motion","parameter_shortname":"Motion","parameter_mmin":0.0,"parameter_mmax":1.0,"parameter_initial":[0.28],"parameter_type":0}}}},
      {"box":{"id":"instability","maxclass":"live.dial","parameter_enable":1,"varname":"Instability","presentation":1,"presentation_rect":[222,55,52,52],"patching_rect":[240,75,52,52],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Instability","parameter_shortname":"Instability","parameter_mmin":0.0,"parameter_mmax":1.0,"parameter_initial":[0.18],"parameter_type":0}}}},
      {"box":{"id":"texture","maxclass":"live.dial","parameter_enable":1,"varname":"Texture","presentation":1,"presentation_rect":[290,55,52,52],"patching_rect":[310,75,52,52],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Texture","parameter_shortname":"Texture","parameter_mmin":0.0,"parameter_mmax":1.0,"parameter_initial":[0.34],"parameter_type":0}}}},
      {"box":{"id":"space","maxclass":"live.dial","parameter_enable":1,"varname":"Space","presentation":1,"presentation_rect":[358,55,52,52],"patching_rect":[380,75,52,52],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Space","parameter_shortname":"Space","parameter_mmin":0.0,"parameter_mmax":1.0,"parameter_initial":[0.52],"parameter_type":0}}}},
      {"box":{"id":"ld","maxclass":"comment","text":"DENSITY","presentation":1,"presentation_rect":[17,108,55,16],"patching_rect":[30,130,55,16]}},
      {"box":{"id":"ls","maxclass":"comment","text":"SPREAD","presentation":1,"presentation_rect":[87,108,55,16],"patching_rect":[100,130,55,16]}},
      {"box":{"id":"lm","maxclass":"comment","text":"MOTION","presentation":1,"presentation_rect":[155,108,55,16],"patching_rect":[170,130,55,16]}},
      {"box":{"id":"li","maxclass":"comment","text":"INSTABILITY","presentation":1,"presentation_rect":[216,108,70,16],"patching_rect":[235,130,70,16]}},
      {"box":{"id":"lt","maxclass":"comment","text":"TEXTURE","presentation":1,"presentation_rect":[289,108,60,16],"patching_rect":[310,130,60,16]}},
      {"box":{"id":"lsp","maxclass":"comment","text":"SPACE","presentation":1,"presentation_rect":[362,108,50,16],"patching_rect":[380,130,50,16]}},
      {"box":{"id":"sd","maxclass":"newobj","text":"send density","patching_rect":[30,175,85,22]}},
      {"box":{"id":"ss","maxclass":"newobj","text":"send spread","patching_rect":[125,175,80,22]}},
      {"box":{"id":"sm","maxclass":"newobj","text":"send motion","patching_rect":[215,175,80,22]}},
      {"box":{"id":"si","maxclass":"newobj","text":"send instability","patching_rect":[305,175,100,22]}},
      {"box":{"id":"st","maxclass":"newobj","text":"send texture","patching_rect":[415,175,80,22]}},
      {"box":{"id":"ssp","maxclass":"newobj","text":"send space","patching_rect":[505,175,75,22]}},
      {"box":{"id":"poly","maxclass":"newobj","text":"poly~ field_voice 64 @parallel 1","patching_rect":[190,255,205,22]}},
      {"box":{"id":"gainl","maxclass":"newobj","text":"*~ 0.75","patching_rect":[150,315,55,22]}},
      {"box":{"id":"gainr","maxclass":"newobj","text":"*~ 0.75","patching_rect":[245,315,55,22]}},
      {"box":{"id":"tapinl","maxclass":"newobj","text":"tapin~ 2500","patching_rect":[390,315,80,22]}},
      {"box":{"id":"tapinr","maxclass":"newobj","text":"tapin~ 2500","patching_rect":[500,315,80,22]}},
      {"box":{"id":"tapoutl","maxclass":"newobj","text":"tapout~ 431.","patching_rect":[390,355,85,22]}},
      {"box":{"id":"tapoutr","maxclass":"newobj","text":"tapout~ 677.","patching_rect":[500,355,85,22]}},
      {"box":{"id":"spaceexpr","maxclass":"newobj","text":"expr $f1 * 0.32","patching_rect":[620,175,95,22]}},
      {"box":{"id":"spacesig","maxclass":"newobj","text":"sig~","patching_rect":[620,215,35,22]}},
      {"box":{"id":"wetl","maxclass":"newobj","text":"*~","patching_rect":[390,405,35,22]}},
      {"box":{"id":"wetr","maxclass":"newobj","text":"*~","patching_rect":[500,405,35,22]}},
      {"box":{"id":"suml","maxclass":"newobj","text":"+~","patching_rect":[175,460,35,22]}},
      {"box":{"id":"sumr","maxclass":"newobj","text":"+~","patching_rect":[270,460,35,22]}},
      {"box":{"id":"liml","maxclass":"newobj","text":"clip~ -0.95 0.95","patching_rect":[160,510,95,22]}},
      {"box":{"id":"limr","maxclass":"newobj","text":"clip~ -0.95 0.95","patching_rect":[270,510,95,22]}},
      {"box":{"id":"plugout","maxclass":"newobj","text":"plugout~","patching_rect":[210,565,60,22]}},
      {"box":{"id":"note","maxclass":"comment","text":"Source-only device. Package/freeze and runtime certification must be completed in Ableton Live 11 before release.","presentation":1,"presentation_rect":[16,138,520,18],"patching_rect":[20,650,720,18]}}
    ],
    "lines": [
      {"patchline":{"source":["density",0],"destination":["sd",0]}},
      {"patchline":{"source":["spread",0],"destination":["ss",0]}},
      {"patchline":{"source":["motion",0],"destination":["sm",0]}},
      {"patchline":{"source":["instability",0],"destination":["si",0]}},
      {"patchline":{"source":["texture",0],"destination":["st",0]}},
      {"patchline":{"source":["space",0],"destination":["ssp",0]}},
      {"patchline":{"source":["space",0],"destination":["spaceexpr",0]}},
      {"patchline":{"source":["spaceexpr",0],"destination":["spacesig",0]}},
      {"patchline":{"source":["poly",0],"destination":["gainl",0]}},
      {"patchline":{"source":["poly",1],"destination":["gainr",0]}},
      {"patchline":{"source":["gainl",0],"destination":["tapinl",0]}},
      {"patchline":{"source":["gainr",0],"destination":["tapinr",0]}},
      {"patchline":{"source":["tapoutl",0],"destination":["wetl",0]}},
      {"patchline":{"source":["tapoutr",0],"destination":["wetr",0]}},
      {"patchline":{"source":["spacesig",0],"destination":["wetl",1]}},
      {"patchline":{"source":["spacesig",0],"destination":["wetr",1]}},
      {"patchline":{"source":["gainl",0],"destination":["suml",0]}},
      {"patchline":{"source":["wetl",0],"destination":["suml",1]}},
      {"patchline":{"source":["gainr",0],"destination":["sumr",0]}},
      {"patchline":{"source":["wetr",0],"destination":["sumr",1]}},
      {"patchline":{"source":["suml",0],"destination":["liml",0]}},
      {"patchline":{"source":["sumr",0],"destination":["limr",0]}},
      {"patchline":{"source":["liml",0],"destination":["plugout",0]}},
      {"patchline":{"source":["limr",0],"destination":["plugout",1]}}
    ],
    "parameters": {
      "density":["Density","Density",0],
      "spread":["Spread","Spread",0],
      "motion":["Motion","Motion",0],
      "instability":["Instability","Instability",0],
      "texture":["Texture","Texture",0],
      "space":["Space","Space",0],
      "parameterbanks": {}
    },
    "dependency_cache": [
      {"name":"field_voice.maxpat","type":"JSON","implicit":1}
    ],
    "autosave": 0
  }
}
